import type { CardData } from "./dataTypes";

export const PROJECT_DATA: CardData[] = [
  {
    name: "Happy Hour Hunt",
    lastUpdated: "6/17/24",
    techsUsed: ["Next.js", "TypeScript", "HTML5", "Tailwind CSS"],
    description:
      "A Yelp-style platform aimed at helping users discover and engage with local happy hours.",
    liveButtonText: "Visit Site",
    liveLink: "https://www.happyhourhunt.net",
    imagePath: "/opengraphImages/h3-og.png",
    tags: ["Personal Project", "Beta Site"],
    role: "Developer & Designer",
    keyFeatures: ["Scalable Data Structuring"],
    type: "Personal Project",
    stage: "Beta - Front-End Development",
  },
  {
    name: "LifeGuide Healing",
    lastUpdated: "6/14/24",
    techsUsed: ["Next.js", "TypeScript", "HTML5", "Tailwind", "Formspark"],
    description:
      "Client Project including full branding and design package for a holistic health website.",
    repoURL: "https://github.com/jduncan017/lifeguide-holistic-healing",
    liveButtonText: "Visit Site",
    liveLink: "https://lifeguidehealing.com/",
    imagePath: "/opengraphImages/lhh-og.png",
    tags: ["Next.js", "Client Project"],
    role: "Developer & Designer",
    keyFeatures: [
      "Brand design & strategy using Figma",
      "Server-side rendering",
    ],
    type: "Client - Brand & Web Design",
    stage: "Front-End Development",
  },
  {
    name: "Cifernoise",
    lastUpdated: "6/20/24",
    techsUsed: ["Duda", "EmbedSocial"],
    description: "Website for a popular silent disco company in Denver, CO.",
    liveButtonText: "Visit Site",
    liveLink: "https://www.cifernoiseproductions.com",
    imagePath: "/opengraphImages/cifernoise-og.png",
    tags: ["Client Project", "Website Redesign"],
    role: "Designer",
    keyFeatures: ["Web Design"],
    type: "Client - Redesign",
    stage: "Completed",
  },
  {
    name: "Ryan Insurance",
    lastUpdated: "6/05/24",
    techsUsed: ["Framer", "Figma", "Formspark"],
    description:
      "Website for an insurance company that sells life, disability, and long-term care insurances.",
    liveButtonText: "Visit Site",
    liveLink: "https://www.ryanpretection.com",
    imagePath: "/opengraphImages/rpi-og.png",
    tags: ["Client Project", "Next.js"],
    role: "Designer",
    keyFeatures: [
      "Framer Motion Animations",
      "Contact form using FormSpark API",
    ],
    type: "Client - Brand & Web Design",
    stage: "Completed",
  },
  {
    name: "Tailwind Plugin",
    lastUpdated: "5/8/24",
    techsUsed: ["TypeScript"],
    description:
      "VS Code plugin that hides excess tailwind code and allows for naming classes.",
    liveButtonText: "View Plugin",
    repoURL: "https://github.com/jduncan017/tailwind-fold-with-class-names",
    liveLink:
      "https://marketplace.visualstudio.com/items?itemName=jduncan017.tailwind-fold-with-class-names",
    imagePath: "/opengraphImages/tailwind-og.png",
    tags: ["Typescript", "VS Code Plugin"],
    role: "Developer",
    keyFeatures: ["VsCode Plugin"],
    type: "Personal Project",
    stage: "Completed",
  },
  {
    name: "John Gerard",
    lastUpdated: "6/15/24",
    techsUsed: [
      "Next.js",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Nodemailer",
      "REST API",
    ],
    description:
      "Client project including full branding and design package for a woodworking company.",
    repoURL: "https://github.com/jduncan017/jgsite",
    liveButtonText: "Visit Site",
    liveLink: "https://www.johngerardwoodwork.com",
    imagePath: "/opengraphImages/jg-og.webp",
    tags: ["Client Project", "Next.js"],
    role: "Developer & Designer",
    keyFeatures: [
      "Designed for Image Optimization",
      "Interactive Keyboard listeners & tooltips",
    ],
    type: "Client - Brand & Web Design",
    stage: "Back-End Development",
  },
  {
    name: "Developer Portfolio",
    lastUpdated: "6/21/24",
    techsUsed: [
      "Next.js",
      "TypeScript",
      "Tailwind",
      "tsParticles",
      "Ascernity UI",
      "Framer Motion",
      "HTML5",
      "Formspark",
    ],
    description:
      "My personal developer portfolio showcases my work and experience.",
    repoURL: "https://github.com/jduncan017/portfolio",
    liveButtonText: "Visit Site",
    liveLink: "https://www.joshuaduncan.info",
    imagePath: "/opengraphImages/portfolio-og.png",
    tags: ["Typescript", "Next.js"],
    role: "Developer & Designer",
    keyFeatures: [
      "React Hooks and Context Providers",
      "Framer Motion Animations",
    ],
    type: "Personal Project",
    stage: "Completed",
  },
];
