import type { CardData } from "./dataTypes";

export const PROJECT_DATA: CardData[] = [
  {
    name: "DigitalNova Studio",
    lastUpdated: "9/23/24",
    tagsFull: ["Framer", "AWS", "Cloudfront"],
    description: "Web Design & Development Studio",
    liveButtonText: "Visit Site",
    liveLink: "https://digitalnovastudio.com",
    imagePath: "/opengraphImages/digitalnova-og.png",
    tags: ["Personal Business", "Design"],
    role: "Founder",
    keyFeatures: [
      "Sticky scoll sections",
      "Custom animations",
      "Data hosted in S3 bucket and served with Cloudfront CDN",
    ],
    type: "Personal Business",
    stage: "Live",
  },
  {
    name: "Optiiflo",
    lastUpdated: "9/23/24",
    tagsFull: ["Next.js", "TypeScript", "HTML5", "Tailwind CSS"],
    description:
      "Workflow managament application for Agencies and Freelancers.",
    liveButtonText: "Visit Site",
    liveLink: "https://mvp.optiiflo.com",
    imagePath: "/opengraphImages/optiiflo-og.jpg",
    tags: ["Startup", "Next.js"],
    role: "Lead Developer & Co-Designer",
    keyFeatures: [
      "Global state management",
      "Server-side rendering",
      "Scalable data structuring",
    ],
    type: "Startup Project",
    stage: "Beta - Front-End Development",
  },
  {
    name: "Straightforward Job Site",
    lastUpdated: "9/23/24",
    tagsFull: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "graphQL",
      "Java Server",
    ],
    description:
      "A job site for everyone focused on simplicity, fairness, and transparency.",
    liveButtonText: "Visit Site",
    liveLink: "https://www.straightforwardjobsite.com",
    imagePath: "/opengraphImages/sfjs-og.png",
    tags: ["Startup", "Next.js"],
    role: "Lead Front-End Developer",
    keyFeatures: ["User Profiles", "Job Postings", "Application Tracking"],
    type: "Startup Project",
    stage: "Landing Page, App Under Development",
  },
  {
    name: "Happy Hour Hunt",
    lastUpdated: "6/17/24",
    tagsFull: ["Next.js", "TypeScript", "HTML5", "Tailwind CSS"],
    description:
      "A Yelp-style platform aimed at helping users discover and engage with local happy hours.",
    liveButtonText: "Visit Site",
    liveLink: "https://www.happyhourhunt.net",
    imagePath: "/opengraphImages/h3-og.png",
    tags: ["Personal Project", "Next.js"],
    role: "Developer & Designer",
    keyFeatures: ["Scalable Data Structuring"],
    type: "Personal Project",
    stage: "Beta - Front-End Development",
  },
  {
    name: "LifeGuide Healing",
    lastUpdated: "6/14/24",
    tagsFull: ["Next.js", "TypeScript", "HTML5", "Tailwind", "Formspark"],
    description:
      "Client Project including full branding and design package for a holistic health website.",
    repoURL: "https://github.com/jduncan017/lifeguide-holistic-healing",
    liveButtonText: "Visit Site",
    liveLink: "https://lifeguidehealing.com/",
    imagePath: "/opengraphImages/lhh-og.png",
    tags: ["Next.js", "Client Project"],
    role: "Developer & Designer",
    keyFeatures: [
      "Brand design & strategy using Figma",
      "Server-side rendering",
    ],
    type: "Client - Brand & Web Design",
    stage: "Front-End Development",
  },
  {
    name: "Cifernoise",
    lastUpdated: "6/20/24",
    tagsFull: ["Duda", "EmbedSocial"],
    description: "Website for a popular silent disco company in Denver, CO.",
    liveButtonText: "Visit Site",
    liveLink: "https://www.cifernoiseproductions.com",
    imagePath: "/opengraphImages/cifernoise-og.png",
    tags: ["Client Project", "Website Redesign"],
    role: "Designer",
    keyFeatures: ["Web Design"],
    type: "Client - Redesign",
    stage: "Completed",
  },
  {
    name: "Ryan Insurance",
    lastUpdated: "6/05/24",
    tagsFull: ["Framer", "Figma", "Formspark"],
    description:
      "Website for an insurance company that sells life, disability, and long-term care insurances.",
    liveButtonText: "Visit Site",
    liveLink: "https://www.ryanpretection.com",
    imagePath: "/opengraphImages/rpi-og.png",
    tags: ["Client Project", "Next.js"],
    role: "Designer",
    keyFeatures: [
      "Framer Motion Animations",
      "Contact form using FormSpark API",
    ],
    type: "Client - Brand & Web Design",
    stage: "Completed",
  },
  {
    name: "Tailwind Plugin",
    lastUpdated: "5/8/24",
    tagsFull: ["TypeScript"],
    description:
      "VS Code plugin that hides excess tailwind code and allows for naming classes.",
    liveButtonText: "View Plugin",
    repoURL: "https://github.com/jduncan017/tailwind-fold-with-class-names",
    liveLink:
      "https://marketplace.visualstudio.com/items?itemName=jduncan017.tailwind-fold-with-class-names",
    altName: "Visual Studio Marketplace",
    imagePath: "/opengraphImages/tailwind-og.png",
    tags: ["Typescript", "VS Code Plugin"],
    role: "Developer",
    keyFeatures: ["VsCode Plugin"],
    type: "Personal Project",
    stage: "Completed",
  },
  {
    name: "John Gerard",
    lastUpdated: "6/15/24",
    tagsFull: [
      "Next.js",
      "TypeScript",
      "HTML5",
      "CSS3",
      "Nodemailer",
      "REST API",
    ],
    description:
      "Client project including full branding and design package for a woodworking company.",
    repoURL: "https://github.com/jduncan017/jgsite",
    liveButtonText: "Visit Site",
    liveLink: "https://www.johngerardwoodwork.com",
    altName: "John Gerard Woodwork",
    imagePath: "/opengraphImages/jg-og.webp",
    tags: ["Client Project", "Next.js"],
    role: "Developer & Designer",
    keyFeatures: [
      "Designed for Image Optimization",
      "Interactive Keyboard listeners & tooltips",
    ],
    type: "Client - Brand & Web Design",
    stage: "Back-End Development",
  },
  {
    name: "Developer Portfolio",
    lastUpdated: "6/21/24",
    tagsFull: [
      "Next.js",
      "TypeScript",
      "Tailwind",
      "tsParticles",
      "Ascernity UI",
      "Framer Motion",
      "HTML5",
      "Formspark",
    ],
    description:
      "My personal developer portfolio showcases my work and experience.",
    repoURL: "https://github.com/jduncan017/portfolio",
    liveButtonText: "Visit Site",
    liveLink: "https://www.joshuaduncan.info",
    imagePath: "/opengraphImages/portfolio-opengraph.png",
    altName: "You're already here!",
    tags: ["Typescript", "Next.js"],
    role: "Developer & Designer",
    keyFeatures: [
      "React Hooks and Context Providers",
      "Framer Motion Animations",
    ],
    type: "Personal Project",
    stage: "Completed",
  },
];
