export const RESUME_DATA = {
  resumeURL: "https://jduncan017.github.io/resume/JoshDuncan.pdf",
  gitHubURL: "https://github.com/jduncan017",
  twitterURL: "https://twitter.com/Jduncan017",
  linkedInURL: "https://www.linkedin.com/in/jduncan017/",
  bioDescription1: `I'm Josh, a full-stack developer with a diverse career history including roles dealing with project management, 
  brand development, design, marketing, and entrepreneurship.`,
  bioDescription2: `Currently, I'm working as a freelance brand strategist and web developer, enjoying the creative freedom of the client process. 
  However, I entered the tech industry with the goal of working with technology to tackle real-world issues, and I'm actively seeking the right opportunity for the next step in my career.`,
  bioDescription3: `I'm passionate about the work I do and get fully immersed in whatever project I'm currently working on. I'm eager to leverage my skillset with
  a new company where I can have a positive influence for both the business and it's users!`,
  education: [
    {
      school: "Monroe Community College",
      position: "Associate of Science - Focus: Chemical Engineering",
      time: "September 2009 - June 2012",
      description: [
        "Notable strengths in logic, sciences, and high-level math, including calculus and differential equations.",
        "Other relevant career studies include communications, graphic design, and economics.",
      ],
    },
  ],
  jobs: [
    {
      name: "TripleTen by Yandex",
      position: "Graduate Full-Stack Software Developer Program",
      time: "January 2023 - January 2024",
      description: [
        "Completed 1000+ hours of hands-on coding experience in JavaScript, React, Node.js, HTML5, and CSS3, using BEM methods, studying best practices and modern approaches to design challenges.",
        "Developed several responsive single-page applications, focusing on efficiency and user experience.",
        "Studied and implemented front-end and back-end aspects of applications, including database modeling, user authentication, REST APIs, web deployment, and modern UI/UX.",
        "Finished my final project using Figma, Next.js 14, and PostgreSQL to develop a business site from start to finish for a real-world client.",
      ],
    },
    {
      name: "Team Enterprises",
      position: "Brand Ambassador (Santa Teresa Rum)",
      time: "Denver, CO | September 2022 - January 2023",
      description: [
        "Consistently hit 200% of my KPI targets, showcasing my ability to exceed goals and manage priorities.",
        "Designed and executed marketing campaigns that led to a 60% increase in product sales across my accounts in the first year, which was triple that of my 20% target metric.",
        "Collaborated with the local team to achieve a 150% increase in sales in the Colorado market within the first year, highlighting strong teamwork and communication skills.",
        "Surpassed all sales and engagement targets while managing and staying under budget.",
      ],
    },
    {
      name: "Adrift Tiki Bar",
      position: "General Manager | Beverage Director",
      time: "Denver, CO | January 2017 - April 2022",
      description: [
        "Transformed a struggling business into a profitable high-end restaurant, increasing sales by 30% in the first year and doubling them over my 5-year tenure. Achieved profitability within the first year.",
        "Fostered a team-oriented culture emphasizing personal growth, significantly reducing employee turnover and increasing average employee tenure from around six months to over two years.",
        "Developed and managed a craft cocktail program that received recognition in local and national publications, balancing cost efficiency with a high standard of quality",
        "Streamlined standards of procedure to optimize operations, reducing overall labor costs.",
        "Identified and capitalized on new revenue streams, including to-go, retail sales, and private events.",
        "Managed and updated all digital platforms, including social media and WordPress sites.",
      ],
    },
  ],
  techSkillz: [
    "JavaScript",
    "TypeScript",
    "HTML5",
    "CSS3 / Tailwind",
    "React",
    "Next.js 14",
    "Node.js",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "GraphQL",
    "DNS & Domain Management",
    "Vercel",
    "Google Cloud",
    "Figma",
    "Canva",
    "Jest",
    "NPM / Yarn",
    "Git / GitHub",
  ],
};
